export const BOOKS_REQUEST = "BOOKS_REQUEST";
export const BOOKS_REQUEST_SUCCESS = "BOOKS_REQUEST_SUCCESS";
export const BOOKS_REQUEST_FAILED = "BOOKS_REQUEST_FAILED";
export const BOOKS_DETAILS_REQUEST = "BOOKS_DETAILS_REQUEST";
export const BOOKS_DETAILS_REQUEST_SUCCESS = "BOOKS_DETAILS_REQUEST_SUCCESS";
export const BOOKS_DETAILS_REQUEST_FAILED = "BOOKS_DETAILS_REQUEST_FAILED";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const BASE_URL = "http://localhost:8080";
