export const BOOKS_REQUEST = "BOOKS_REQUEST";
export const BOOKS_REQUEST_SUCCESS = "BOOKS_REQUEST_SUCCESS";
export const BOOKS_REQUEST_FAILED = "BOOKS_REQUEST_FAILED";
export const BOOKS_DETAILS_REQUEST = "BOOKS_DETAILS_REQUEST";
export const BOOKS_DETAILS_REQUEST_SUCCESS = "BOOKS_DETAILS_REQUEST_SUCCESS";
export const BOOKS_DETAILS_REQUEST_FAILED = "BOOKS_DETAILS_REQUEST_FAILED";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS";
export const USER_LOGIN_REQUEST_FAILED = "USER_LOGIN_REQUEST_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_REQUEST_SUCCESS = "USER_REGISTER_REQUEST_SUCCESS";
export const USER_REGISTER_REQUEST_FAILED = "USER_REGISTER_REQUEST_FAILED";

export const BASE_URL = "http://localhost:8080";
