export const BOOKS_REQUEST = "BOOKS_REQUEST";
export const BOOKS_REQUEST_SUCCESS = "BOOKS_REQUEST_SUCCESS";
export const BOOKS_REQUEST_FAILED = "BOOKS_REQUEST_FAILED";
export const BOOKS_DETAILS_REQUEST = "BOOKS_DETAILS_REQUEST";
export const BOOKS_DETAILS_REQUEST_SUCCESS = "BOOKS_DETAILS_REQUEST_SUCCESS";
export const BOOKS_DETAILS_REQUEST_FAILED = "BOOKS_DETAILS_REQUEST_FAILED";
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const REFRESH_CART = "REFRESH_CART";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS";
export const USER_LOGIN_REQUEST_FAILED = "USER_LOGIN_REQUEST_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_REQUEST_SUCCESS = "USER_REGISTER_REQUEST_SUCCESS";
export const USER_REGISTER_REQUEST_FAILED = "USER_REGISTER_REQUEST_FAILED";
export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_REQUEST_SUCCESS =
  "USER_PROFILE_UPDATE_REQUEST_SUCCESS";
export const USER_PROFILE_UPDATE_REQUEST_FAILED =
  "USER_PROFILE_UPDATE_REQUEST_FAILED";
export const SHIPPING_ADDRESS = "USER_SHIPPING_ADDRESS";
export const PAYMENT_METHOD = "PAYMENT_METHOD";
export const CART = "CART";
export const SHIPPED = "SHIPPED";
export const DELIVERED = "DELIVERED";
export const CANCELLED = "CANCELLED";
export const CREDITCARD = "CREDITCARD";
export const RAZORPAY = "RAZORPAY";
export const SUCCESS = "SUCCESS";
export const FAILED = "FAILED";
export const PROCESSING = "PROCESSING";
export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAILED = "ORDER_CREATE_FAILED";
export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_REQUEST_FAILED = "ORDER_DETAILS_REQUEST_FAILED";
export const ORDER_DETAILS_REQUEST_SUCCESS = "ORDER_DETAILS_REQUEST_SUCCESS";
export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const USER_ORDERS_REQUEST_SUCCESS = "USER_ORDERS_REQUEST_SUCCESS";
export const USER_ORDERS_REQUEST_FAILED = "USER_ORDERS_REQUEST_FAILED";
export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_REQUEST_SUCCESS = "GET_ALL_USERS_REQUEST_SUCCESS";
export const GET_ALL_USERS_REQUEST_FAILED = "GET_ALL_USERS_REQUEST_FAILED";
export const REMOVE_USER_REQUEST = "REMOVE_USER_REQUEST";
export const REMOVE_USER_REQUEST_SUCCESS = "REMOVE_USER_REQUEST_SUCCESS";
export const REMOVE_USER_REQUEST_FAILED = "REMOVE_USER_REQUEST_FAILED";
export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_REQUEST_SUCCESS = "UPDATE_ORDER_REQUEST_SUCCESS";
export const UPDATE_ORDER_REQUEST_FAILED = "UPDATE_ORDER_REQUEST_FAILED";
export const UPDATE_BOOK_COUNT_REQUEST = "UPDATE_BOOK_COUNT_REQUEST";
export const UPDATE_BOOK_COUNT_REQUEST_SUCCESS =
  "UPDATE_BOOK_COUNT_REQUEST_SUCCESS";
export const UPDATE_BOOK_COUNT_REQUEST_FAILED =
  "UPDATE_BOOK_COUNT_REQUEST_FAILED";
export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_REQUEST_SUCCESS = "CREATE_REVIEW_REQUEST_SUCCESS";
export const CREATE_REVIEW_REQUEST_FAILED = "CREATE_REVIEW_REQUEST_FAILED";
export const GET_ALL_REVIEWS_REQUEST = "GET_ALL_REVIEWS_REQUEST";
export const GET_ALL_REVIEWS_REQUEST_SUCCESS =
  "GET_ALL_REVIEWS_REQUEST_SUCCESS";
export const GET_ALL_REVIEWS_REQUEST_FAILED = "GET_ALL_REVIEWS_REQUEST_FAILED";
export const GET_BOOKS_FROM_GOOGLE_REQUEST = "GET_BOOKS_FROM_GOOGLE_REQUEST";
export const GET_BOOKS_FROM_GOOGLE_REQUEST_SUCCESS =
  "GET_BOOKS_FROM_GOOGLE_REQUEST_SUCCESS";
export const GET_BOOKS_FROM_GOOGLE_REQUEST_FAILED =
  "GET_BOOKS_FROM_GOOGLE_REQUEST_FAILED";

export const BASE_URL = "http://localhost:8080";
